global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8080"]
  
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

remote_write:
  - url: https://prometheus-prod-XX-prod-YY.grafana.net/api/prom/push # Reemplazar por URL real de mi stack
    basic_auth:
      username: "GRAFANA_CLOUD_INSTANCE_ID"
      password: "GRAFANA_CLOUD_METRICS_PUBLISHER_API_KEY"
